// Cache indices

#define IDX_ACTIVE 0
#define IDX_MODECACHED 1
#define IDX_LIGHTCACHED 2
#define IDX_ZOOMCACHED 3
#define IDX_LASTSAMPLE 4
#define IDX_HANDLESCREATED 5
#define IDX_RANGEFACTORCACHED 6
#define IDX_TESTPOSCACHED 7
#define IDX_ITEMCLASSCACHED 8
#define IDX_GENINDEXCACHED 9
#define IDX_COLORPRESETCACHED 10
#define IDX_MAXRANGECACHED 11
#define IDX_MINZOOMOFFSETCACHED 12
